### ISSUE TITLE
Not showing active status for qualified if status is change to Propose

### ISSUE THREAD

**Issue by Fenil27** [rahulgawale/Lightning-Path-in-Lwc#1]
value is changed for "selectedUpTo" from 0 to 1. 

<img width="679" alt="image" src="https://github.com/rahulgawale/Lightning-Path-in-Lwc/assets/135974070/3a5f4bba-19ff-45ef-b0de-83e5aa533a6d">

**Comment by rahulgawale** [comment]
Hi @Fenil27 thank you for reporting the issue. Please note that now you can use the native lightning progress indicator component to achieve this functionality, so I would recommend you use that one. Here is the link for the same: https://developer.salesforce.com/docs/component-library/bundle/lightning-progress-indicator/example

Also, I am not actively maintaining this particular repo because of some personal time limitations. I might fix this issue but not in the near future. I really appreciate you to report the issue. Sorry for the inconvenience.

**Comment by Fenil27** [comment]
Hi @rahulgawale,

Thanks for your quick response. I have already resolve this issue.
Thanks very much for sharing this. It's very useful and becuase of you I have learned this new custom path functionality.

**Comment by Fenil27** [comment]
Hello @rahulgawale,

It's working in one of sandbox org. but, it's not working in another org. 
Getting below error from browser console and it's continous buffering, not updating status itself:

<img width="369" alt="image" src="https://github.com/rahulgawale/Lightning-Path-in-Lwc/assets/135974070/01494977-8281-47c1-95cc-51e26f63cd3b">

**Comment by rahulgawale** [comment]
@Fenil27 can you share your code snippets?

**Comment by Fenil27** [comment]
@rahulgawale - Same I am referring which you have mention in GitHub. 
Strange, It's working in one of the org but not working in another org.

**Comment by rahulgawale** [comment]
@Fenil27 the error you are getting is related to CSP policy, please add the urls to CSP policy in setup. seems like you are using google map or some other Google product

**Comment by Fenil27** [comment]
@rahulgawale Yes, I have check that CSP policy. But, I am not using google map or some other Google product. I have used the same code written in GitHub. It's working in one org and not working in another org.

**Comment by Fenil27** [comment]
@rahulgawale - It's working now. May be it's a loading problem because of lwc. Thanks very much again. Haapy to learn something new from you :)

**Comment by Fenil27** [comment]
I am closing this issue.
